// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';w
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4kHXhZpvEIoOolMUu1BIkXUBA8PELLt8',
    appId: '1:1096289604010:web:1b981c5e57fed0fab85bd3',
    messagingSenderId: '1096289604010',
    projectId: 'intelligrow-86e8e',
    authDomain: 'intelligrow-86e8e.firebaseapp.com',
    storageBucket: 'intelligrow-86e8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJERkYmZ6Ry18y3gtfASkp-oMsYOgM2A',
    appId: '1:1096289604010:android:ab530ffa9dcc8066b85bd3',
    messagingSenderId: '1096289604010',
    projectId: 'intelligrow-86e8e',
    storageBucket: 'intelligrow-86e8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIPEI2Nq20T6UlG7m6B6cu_-WiyaswquQ',
    appId: '1:1096289604010:ios:2be1d36ced49ea3db85bd3',
    messagingSenderId: '1096289604010',
    projectId: 'intelligrow-86e8e',
    storageBucket: 'intelligrow-86e8e.appspot.com',
    iosClientId: '1096289604010-estfbs0q6evedrl19i6omcgg9l7da016.apps.googleusercontent.com',
    iosBundleId: 'com.IntelliGrow.intelliGrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIPEI2Nq20T6UlG7m6B6cu_-WiyaswquQ',
    appId: '1:1096289604010:ios:538c716610ed0f30b85bd3',
    messagingSenderId: '1096289604010',
    projectId: 'intelligrow-86e8e',
    storageBucket: 'intelligrow-86e8e.appspot.com',
    iosClientId: '1096289604010-0qjvlraapbi9rknn0b5nh5fein0g5rh1.apps.googleusercontent.com',
    iosBundleId: 'com.IntelliGrow.intelliGrow.RunnerTests',
  );
}
